In [1]:
# ============================================================
# Install the required libraries.
#
# yfinance : Downloads financial statements from Yahoo Finance.
# openpyxl : Used for exporting Excel files.
# ============================================================

!pip install yfinance openpyxl

Requirement already satisfied: yfinance in /usr/local/lib/python3.12/dist-packages (0.2.66)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: pandas>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.2.2)
Requirement already satisfied: numpy>=1.16.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.0.2)
Requirement already satisfied: requests>=2.31 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.32.4)
Requirement already satisfied: multitasking>=0.0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.0.13)
Requirement already satisfied: platformdirs>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.10.0)
Requirement already satisfied: pytz>=2022.5 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2025.2)
Requirement already satisfied: frozendict>=2.3.4 in /usr/local/lib/python3.12/dist-packages (from yfinance) (2.4.7)
Requirement already satisfied: peewee>=3.16.2 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.2.2)
Requirement already satisfied: beautifulsoup4>=4.11.1 in /usr/local/lib/python3.12/dist-packages (from yfinance) (4.13.5)
Requirement already satisfied: curl_cffi>=0.7 in /usr/local/lib/python3.12/dist-packages (from yfinance) (0.15.0)
Requirement already satisfied: protobuf>=3.19.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (5.29.6)
Requirement already satisfied: websockets>=13.0 in /usr/local/lib/python3.12/dist-packages (from yfinance) (15.0.1)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (2.8.4)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from beautifulsoup4>=4.11.1->yfinance) (4.16.0)
Requirement already satisfied: cffi>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2.1.0)
Requirement already satisfied: certifi>=2024.2.2 in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (2026.6.17)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from curl_cffi>=0.7->yfinance) (13.9.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.3.0->yfinance) (2026.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.31->yfinance) (2.5.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=2.0.0->curl_cffi>=0.7->yfinance) (3.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.3.0->yfinance) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->curl_cffi>=0.7->yfinance) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->curl_cffi>=0.7->yfinance) (0.1.2)

In [2]:
# ============================================================
# Import the required libraries.
#
# pandas   : Data manipulation and analysis.
# yfinance : Download company financial statements.
# ============================================================

import pandas as pd
import yfinance as yf

# Historical Financial Dataset Creation

In the previous notebook, the financial statements of a
single company were explored to understand their structure.

In this notebook, the same process is automated for
multiple companies.

For every company, historical information from the

• Income Statement
• Balance Sheet
• Cash Flow Statement

will be downloaded and combined into one historical
financial dataset.

The final dataset will be used throughout the remaining
chapters of this book.

In [4]:
companies = [

"ADANIENT.NS",
"ADANIPORTS.NS",
"APOLLOHOSP.NS",
"ASIANPAINT.NS",
"AXISBANK.NS",
"BAJAJ-AUTO.NS",
"BAJFINANCE.NS",
"BAJAJFINSV.NS",
"BEL.NS",
"BHARTIARTL.NS",
"CIPLA.NS",
"COALINDIA.NS",
"DRREDDY.NS",
"EICHERMOT.NS",
"ETERNAL.NS",
"GRASIM.NS",
"HCLTECH.NS",
"HDFCBANK.NS",
"HDFCLIFE.NS",
"HEROMOTOCO.NS",
"HINDALCO.NS",
"HINDUNILVR.NS",
"ICICIBANK.NS",
"INDUSINDBK.NS",
"INFY.NS",
"ITC.NS",
"JIOFIN.NS",
"JSWSTEEL.NS",
"KOTAKBANK.NS",
"LT.NS",
"M&M.NS",
"MARUTI.NS",
"NESTLEIND.NS",
"NTPC.NS",
"ONGC.NS",
"POWERGRID.NS",
"RELIANCE.NS",
"SBILIFE.NS",
"SBIN.NS",
"SHRIRAMFIN.NS",
"SUNPHARMA.NS",
"TATACONSUM.NS",
"TATAMOTORS.NS",
"TATASTEEL.NS",
"TCS.NS",
"TECHM.NS",
"TITAN.NS",
"TRENT.NS",
"ULTRACEMCO.NS",
"WIPRO.NS"

]

print(f"Total Companies : {len(companies)}")

Total Companies : 50

In [5]:
# ============================================================
# Create an empty list.
#
# The financial information extracted for every company
# and every financial year will be stored in this list.
#
# Later, the list will be converted into a Pandas DataFrame.
# ============================================================

historical_dataset = []

In [6]:
# ============================================================
# Create a helper function.
#
# Financial statements are stored as Pandas DataFrames.
#
# This function retrieves an entire historical series for a
# specified financial variable.
#
# If a variable is unavailable for a company, an empty
# Pandas Series is returned instead of generating an error.
# ============================================================

def get_series(statement, variable):

    try:
        return statement.loc[variable]

    except:
        return pd.Series(dtype="float64")

In [7]:
# ============================================================
# Download the financial statements of Reliance Industries.
#
# This step verifies that the extraction process works
# correctly before applying it to all companies.
# ============================================================

company = yf.Ticker("RELIANCE.NS")

info = company.info

income = company.financials

balance = company.balance_sheet

cashflow = company.cashflow

In [8]:
# ============================================================
# Extract historical financial variables.
#
# Each variable is stored as a historical Pandas Series
# containing values for multiple financial years.
# ============================================================

revenue = get_series(income, "Total Revenue")
gross_profit = get_series(income, "Gross Profit")
operating_income = get_series(income, "Operating Income")
ebit = get_series(income, "EBIT")
ebitda = get_series(income, "EBITDA")
net_income = get_series(income, "Net Income")

total_assets = get_series(balance, "Total Assets")
current_assets = get_series(balance, "Current Assets")
cash = get_series(balance, "Cash And Cash Equivalents")
inventory = get_series(balance, "Inventory")
accounts_receivable = get_series(balance, "Accounts Receivable")

total_liabilities = get_series(balance, "Total Liabilities Net Minority Interest")
current_liabilities = get_series(balance, "Current Liabilities")
long_term_debt = get_series(balance, "Long Term Debt")
total_debt = get_series(balance, "Total Debt")
shareholders_equity = get_series(balance, "Stockholders Equity")
retained_earnings = get_series(balance, "Retained Earnings")

operating_cash_flow = get_series(cashflow, "Operating Cash Flow")
investing_cash_flow = get_series(cashflow, "Investing Cash Flow")
financing_cash_flow = get_series(cashflow, "Financing Cash Flow")
capital_expenditure = get_series(cashflow, "Capital Expenditure")
free_cash_flow = get_series(cashflow, "Free Cash Flow")

In [10]:
# ============================================================
# Create the Historical Financial Dataset.
#
# This loop downloads the financial statements of every
# company, extracts historical values for each financial
# year, and stores one record per company per year.
# ============================================================

for symbol in companies:

    print(f"Processing {symbol}")

    try:

        company = yf.Ticker(symbol)

        info = company.info
        income = company.financials
        balance = company.balance_sheet
        cashflow = company.cashflow

        # Company Information
        company_name = info.get("longName")
        ticker = info.get("symbol")
        sector = info.get("sector")
        industry = info.get("industry")

        # Income Statement
        revenue = get_series(income, "Total Revenue")
        gross_profit = get_series(income, "Gross Profit")
        operating_income = get_series(income, "Operating Income")
        ebit = get_series(income, "EBIT")
        ebitda = get_series(income, "EBITDA")
        net_income = get_series(income, "Net Income")

        # Balance Sheet
        total_assets = get_series(balance, "Total Assets")
        current_assets = get_series(balance, "Current Assets")
        cash = get_series(balance, "Cash And Cash Equivalents")
        total_liabilities = get_series(balance, "Total Liabilities Net Minority Interest")
        total_debt = get_series(balance, "Total Debt")
        shareholders_equity = get_series(balance, "Stockholders Equity")

        # Cash Flow Statement
        operating_cash_flow = get_series(cashflow, "Operating Cash Flow")
        investing_cash_flow = get_series(cashflow, "Investing Cash Flow")
        financing_cash_flow = get_series(cashflow, "Financing Cash Flow")
        capital_expenditure = get_series(cashflow, "Capital Expenditure")
        free_cash_flow = get_series(cashflow, "Free Cash Flow")

        # Determine available financial years
        years = revenue.index

        for year in years:

            financial_data = {

                "Company": company_name,
                "Ticker": ticker,
                "Sector": sector,
                "Industry": industry,
                "Financial Year": year.year,

                "Revenue": revenue.get(year),
                "Gross Profit": gross_profit.get(year),
                "Operating Income": operating_income.get(year),
                "EBIT": ebit.get(year),
                "EBITDA": ebitda.get(year),
                "Net Income": net_income.get(year),

                "Total Assets": total_assets.get(year),
                "Current Assets": current_assets.get(year),
                "Cash": cash.get(year),
                "Total Liabilities": total_liabilities.get(year),
                "Total Debt": total_debt.get(year),
                "Shareholders Equity": shareholders_equity.get(year),

                "Operating Cash Flow": operating_cash_flow.get(year),
                "Investing Cash Flow": investing_cash_flow.get(year),
                "Financing Cash Flow": financing_cash_flow.get(year),
                "Capital Expenditure": capital_expenditure.get(year),
                "Free Cash Flow": free_cash_flow.get(year)

            }

            historical_dataset.append(financial_data)

    except Exception as e:

        print(f"Could not process {symbol}")
        print(e)

Processing ADANIENT.NS
Processing ADANIPORTS.NS
Processing APOLLOHOSP.NS
Processing ASIANPAINT.NS
Processing AXISBANK.NS
Processing BAJAJ-AUTO.NS
Processing BAJFINANCE.NS
Processing BAJAJFINSV.NS
Processing BEL.NS
Processing BHARTIARTL.NS
Processing CIPLA.NS
Processing COALINDIA.NS
Processing DRREDDY.NS
Processing EICHERMOT.NS
Processing ETERNAL.NS
Processing GRASIM.NS
Processing HCLTECH.NS
Processing HDFCBANK.NS
Processing HDFCLIFE.NS
Processing HEROMOTOCO.NS
Processing HINDALCO.NS
Processing HINDUNILVR.NS
Processing ICICIBANK.NS
Processing INDUSINDBK.NS
Processing INFY.NS
Processing ITC.NS
Processing JIOFIN.NS
Processing JSWSTEEL.NS
Processing KOTAKBANK.NS
Processing LT.NS
Processing M&M.NS
Processing MARUTI.NS
Processing NESTLEIND.NS
Processing NTPC.NS
Processing ONGC.NS
Processing POWERGRID.NS
Processing RELIANCE.NS
Processing SBILIFE.NS
Processing SBIN.NS
Processing SHRIRAMFIN.NS
Processing SUNPHARMA.NS
Processing TATACONSUM.NS

ERROR:yfinance:HTTP Error 404: {"quoteSummary":{"result":null,"error":{"code":"Not Found","description":"Quote not found for symbol: TATAMOTORS.NS"}}}

Processing TATAMOTORS.NS
Processing TATASTEEL.NS
Processing TCS.NS
Processing TECHM.NS
Processing TITAN.NS
Processing TRENT.NS
Processing ULTRACEMCO.NS
Processing WIPRO.NS

In [11]:
historical_df = pd.DataFrame(historical_dataset)

historical_df.head()

,Company,Ticker,Sector,Industry,Financial Year,Revenue,Gross Profit,Operating Income,EBIT,EBITDA,...,Current Assets,Cash,Total Liabilities,Total Debt,Shareholders Equity,Operating Cash Flow,Investing Cash Flow,Financing Cash Flow,Capital Expenditure,Free Cash Flow
0,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2026,1.002670e+12,2.620093e+11,8.437760e+10,1.991757e+11,2.605291e+11,...,6.117604e+11,6.266670e+10,1.724221e+12,1.066218e+12,8.092595e+11,2.356910e+10,-2.843801e+11,2.848447e+11,-3.336912e+11,-3.101221e+11
1,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2025,9.771108e+11,3.276082e+11,1.044309e+11,1.536634e+11,1.957767e+11,...,4.094422e+11,3.105780e+10,1.416651e+12,9.147260e+11,5.031397e+11,4.513100e+10,-2.696661e+11,2.265534e+11,-2.987914e+11,-2.536604e+11
2,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2024,9.631615e+11,3.114884e+11,9.012870e+10,8.644370e+10,1.168652e+11,...,3.702690e+11,2.306550e+10,1.165456e+12,6.531015e+11,3.907609e+11,1.031219e+11,-1.908218e+11,8.878680e+10,-2.236591e+11,-1.205372e+11
3,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2023,1.273896e+12,2.061800e+11,6.827980e+10,6.241290e+10,8.677430e+10,...,3.728228e+11,1.882330e+10,1.035978e+12,5.301260e+11,3.305101e+11,1.762646e+11,-1.686009e+11,-1.197520e+10,-1.472472e+11,2.901740e+10
4,Adani Ports and Special Economic Zone Limited,ADANIPORTS.NS,Industrials,Marine Shipping,2026,3.873577e+11,2.343314e+11,1.745082e+11,1.859993e+11,2.411731e+11,...,2.197483e+11,5.161550e+10,8.633328e+11,6.323616e+11,9.612530e+11,2.035625e+11,-1.319070e+11,-5.483400e+10,-1.532031e+11,5.035940e+10

In [12]:
print(historical_df.shape)

(232, 22)

In [13]:
historical_df.head(10)

,Company,Ticker,Sector,Industry,Financial Year,Revenue,Gross Profit,Operating Income,EBIT,EBITDA,...,Current Assets,Cash,Total Liabilities,Total Debt,Shareholders Equity,Operating Cash Flow,Investing Cash Flow,Financing Cash Flow,Capital Expenditure,Free Cash Flow
0,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2026,1.002670e+12,2.620093e+11,8.437760e+10,1.991757e+11,2.605291e+11,...,6.117604e+11,6.266670e+10,1.724221e+12,1.066218e+12,8.092595e+11,2.356910e+10,-2.843801e+11,2.848447e+11,-3.336912e+11,-3.101221e+11
1,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2025,9.771108e+11,3.276082e+11,1.044309e+11,1.536634e+11,1.957767e+11,...,4.094422e+11,3.105780e+10,1.416651e+12,9.147260e+11,5.031397e+11,4.513100e+10,-2.696661e+11,2.265534e+11,-2.987914e+11,-2.536604e+11
2,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2024,9.631615e+11,3.114884e+11,9.012870e+10,8.644370e+10,1.168652e+11,...,3.702690e+11,2.306550e+10,1.165456e+12,6.531015e+11,3.907609e+11,1.031219e+11,-1.908218e+11,8.878680e+10,-2.236591e+11,-1.205372e+11
3,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2023,1.273896e+12,2.061800e+11,6.827980e+10,6.241290e+10,8.677430e+10,...,3.728228e+11,1.882330e+10,1.035978e+12,5.301260e+11,3.305101e+11,1.762646e+11,-1.686009e+11,-1.197520e+10,-1.472472e+11,2.901740e+10
4,Adani Ports and Special Economic Zone Limited,ADANIPORTS.NS,Industrials,Marine Shipping,2026,3.873577e+11,2.343314e+11,1.745082e+11,1.859993e+11,2.411731e+11,...,2.197483e+11,5.161550e+10,8.633328e+11,6.323616e+11,9.612530e+11,2.035625e+11,-1.319070e+11,-5.483400e+10,-1.532031e+11,5.035940e+10
5,Adani Ports and Special Economic Zone Limited,ADANIPORTS.NS,Industrials,Marine Shipping,2025,3.047533e+11,1.838438e+11,1.411690e+11,1.571630e+11,2.009523e+11,...,1.894412e+11,3.406320e+10,7.035889e+11,5.130482e+11,6.243539e+11,1.722628e+11,-9.787270e+10,-6.915520e+10,-8.048920e+10,9.177360e+10
6,Adani Ports and Special Economic Zone Limited,ADANIPORTS.NS,Industrials,Marine Shipping,2024,2.671056e+11,1.539877e+11,1.215320e+11,1.280524e+11,1.669370e+11,...,1.747236e+11,1.575730e+10,6.437487e+11,4.916666e+11,5.294477e+11,1.501758e+11,-6.946550e+10,-7.800110e+10,-7.416300e+10,7.601280e+10
7,Adani Ports and Special Economic Zone Limited,ADANIPORTS.NS,Industrials,Marine Shipping,2023,2.085191e+11,1.179015e+11,9.512750e+10,8.043950e+10,1.146866e+11,...,1.759639e+11,1.121110e+10,6.784611e+11,5.244284e+11,4.555592e+11,1.189950e+11,-1.956008e+11,-2.733800e+10,-9.141040e+10,2.758460e+10
8,Adani Ports and Special Economic Zone Limited,ADANIPORTS.NS,Industrials,Marine Shipping,2022,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Apollo Hospitals Enterprise Limited,APOLLOHOSP.NS,Healthcare,Medical Care Facilities,2026,2.522850e+11,1.215290e+11,2.893200e+10,3.110500e+10,3.986600e+10,...,6.899800e+10,8.113000e+09,1.222240e+11,8.492900e+10,9.480100e+10,2.855700e+10,-2.148200e+10,-4.776000e+09,-1.962000e+10,8.937000e+09

In [14]:
historical_df["Financial Year"].value_counts().sort_index()

Financial Year
2021     1
2022    37
2023    48
2024    48
2025    49
2026    49
Name: count, dtype: int64

In [15]:
historical_df["Company"].nunique()

45

In [16]:
historical_df["Ticker"].nunique()

49

In [17]:
missing = sorted(set(companies) - set(historical_df["Ticker"].unique()))

print(missing)

['TATAMOTORS.NS']

In [18]:
historical_df.columns

Index(['Company', 'Ticker', 'Sector', 'Industry', 'Financial Year', 'Revenue',
       'Gross Profit', 'Operating Income', 'EBIT', 'EBITDA', 'Net Income',
       'Total Assets', 'Current Assets', 'Cash', 'Total Liabilities',
       'Total Debt', 'Shareholders Equity', 'Operating Cash Flow',
       'Investing Cash Flow', 'Financing Cash Flow', 'Capital Expenditure',
       'Free Cash Flow'],
      dtype='object')

In [19]:
historical_df.isnull().sum()

Company                18
Ticker                  0
Sector                  0
Industry                0
Financial Year          0
Revenue                37
Gross Profit           80
Operating Income       80
EBIT                   68
EBITDA                 80
Net Income             37
Total Assets           37
Current Assets         81
Cash                   36
Total Liabilities      37
Total Debt             41
Shareholders Equity    37
Operating Cash Flow    45
Investing Cash Flow    37
Financing Cash Flow    37
Capital Expenditure    38
Free Cash Flow         37
dtype: int64

In [20]:
# ============================================================
# Check the completeness of the historical dataset.
#
# Not every company reports every financial variable.
#
# This summary shows the number of missing values in each
# variable and helps assess the quality of the dataset.
# ============================================================

missing_summary = pd.DataFrame({

    "Missing Values": historical_df.isnull().sum(),

    "Available Values": historical_df.notnull().sum()

})

missing_summary

                     Missing Values  Available Values
Company                          18               214
Ticker                            0               232
Sector                            0               232
Industry                          0               232
Financial Year                    0               232
Revenue                          37               195
Gross Profit                     80               152
Operating Income                 80               152
EBIT                             68               164
EBITDA                           80               152
Net Income                       37               195
Total Assets                     37               195
Current Assets                   81               151
Cash                             36               196
Total Liabilities                37               195
Total Debt                       41               191
Shareholders Equity              37               195
Operating Cash Flow              45               187
Investing Cash Flow              37               195
Financing Cash Flow              37               195
Capital Expenditure              38               194
Free Cash Flow                   37               195

In [21]:
# ============================================================
# Display the dimensions of the Historical Financial Dataset.
#
# The shape attribute returns:
#
# • Number of observations (rows)
# • Number of variables (columns)
#
# This provides a quick summary of the completed dataset.
# ============================================================

print("Dataset Shape:", historical_df.shape)

Dataset Shape: (232, 22)

In [22]:
# ============================================================
# Display the first ten observations.
#
# This provides a quick preview of the completed
# Historical Financial Dataset.
# ============================================================

historical_df.head(10)

,Company,Ticker,Sector,Industry,Financial Year,Revenue,Gross Profit,Operating Income,EBIT,EBITDA,...,Current Assets,Cash,Total Liabilities,Total Debt,Shareholders Equity,Operating Cash Flow,Investing Cash Flow,Financing Cash Flow,Capital Expenditure,Free Cash Flow
0,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2026,1.002670e+12,2.620093e+11,8.437760e+10,1.991757e+11,2.605291e+11,...,6.117604e+11,6.266670e+10,1.724221e+12,1.066218e+12,8.092595e+11,2.356910e+10,-2.843801e+11,2.848447e+11,-3.336912e+11,-3.101221e+11
1,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2025,9.771108e+11,3.276082e+11,1.044309e+11,1.536634e+11,1.957767e+11,...,4.094422e+11,3.105780e+10,1.416651e+12,9.147260e+11,5.031397e+11,4.513100e+10,-2.696661e+11,2.265534e+11,-2.987914e+11,-2.536604e+11
2,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2024,9.631615e+11,3.114884e+11,9.012870e+10,8.644370e+10,1.168652e+11,...,3.702690e+11,2.306550e+10,1.165456e+12,6.531015e+11,3.907609e+11,1.031219e+11,-1.908218e+11,8.878680e+10,-2.236591e+11,-1.205372e+11
3,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2023,1.273896e+12,2.061800e+11,6.827980e+10,6.241290e+10,8.677430e+10,...,3.728228e+11,1.882330e+10,1.035978e+12,5.301260e+11,3.305101e+11,1.762646e+11,-1.686009e+11,-1.197520e+10,-1.472472e+11,2.901740e+10
4,Adani Ports and Special Economic Zone Limited,ADANIPORTS.NS,Industrials,Marine Shipping,2026,3.873577e+11,2.343314e+11,1.745082e+11,1.859993e+11,2.411731e+11,...,2.197483e+11,5.161550e+10,8.633328e+11,6.323616e+11,9.612530e+11,2.035625e+11,-1.319070e+11,-5.483400e+10,-1.532031e+11,5.035940e+10
5,Adani Ports and Special Economic Zone Limited,ADANIPORTS.NS,Industrials,Marine Shipping,2025,3.047533e+11,1.838438e+11,1.411690e+11,1.571630e+11,2.009523e+11,...,1.894412e+11,3.406320e+10,7.035889e+11,5.130482e+11,6.243539e+11,1.722628e+11,-9.787270e+10,-6.915520e+10,-8.048920e+10,9.177360e+10
6,Adani Ports and Special Economic Zone Limited,ADANIPORTS.NS,Industrials,Marine Shipping,2024,2.671056e+11,1.539877e+11,1.215320e+11,1.280524e+11,1.669370e+11,...,1.747236e+11,1.575730e+10,6.437487e+11,4.916666e+11,5.294477e+11,1.501758e+11,-6.946550e+10,-7.800110e+10,-7.416300e+10,7.601280e+10
7,Adani Ports and Special Economic Zone Limited,ADANIPORTS.NS,Industrials,Marine Shipping,2023,2.085191e+11,1.179015e+11,9.512750e+10,8.043950e+10,1.146866e+11,...,1.759639e+11,1.121110e+10,6.784611e+11,5.244284e+11,4.555592e+11,1.189950e+11,-1.956008e+11,-2.733800e+10,-9.141040e+10,2.758460e+10
8,Adani Ports and Special Economic Zone Limited,ADANIPORTS.NS,Industrials,Marine Shipping,2022,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Apollo Hospitals Enterprise Limited,APOLLOHOSP.NS,Healthcare,Medical Care Facilities,2026,2.522850e+11,1.215290e+11,2.893200e+10,3.110500e+10,3.986600e+10,...,6.899800e+10,8.113000e+09,1.222240e+11,8.492900e+10,9.480100e+10,2.855700e+10,-2.148200e+10,-4.776000e+09,-1.962000e+10,8.937000e+09

In [23]:
# ============================================================
# Save the Historical Financial Dataset.
#
# The completed dataset is exported as a CSV file.
#
# This file will be used throughout the remaining chapters
# of this book for financial analytics, forecasting,
# valuation and investment analysis.
# ============================================================

historical_df.to_csv("Historical_Financial_Data.csv", index=False)

print("Historical_Financial_Data.csv has been saved successfully.")

Historical_Financial_Data.csv has been saved successfully.