# Chapter 5: Time Value of Money (TVM)

## Objective

The Time Value of Money (TVM) is one of the most fundamental concepts in finance. It states that a sum of money available today is worth more than the same amount received in the future because today's money can be invested to earn a return.

In this notebook, we will:

- Understand the concept of Time Value of Money.
- Calculate Future Value (FV).
- Calculate Present Value (PV).
- Apply these concepts using real financial data extracted from the Historical Financial Dataset.

In [1]:
# ============================================================
# Import the required libraries.
#
# pandas : Reading and analysing financial data.
# numpy  : Mathematical calculations.
# ============================================================

import pandas as pd
import numpy as np

In [2]:
# ============================================================
# Mount Google Drive.
#
# The Historical Financial Dataset created in the previous
# notebook has been saved in Google Drive.
#
# Mounting Google Drive allows Google Colab to access files
# stored in your personal Drive.
# ============================================================

from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
import glob

file_path = glob.glob(
    "/content/drive/MyDrive/**/Historical_Financial_Data.csv",
    recursive=True
)[0]

print("File found at:", file_path)

File found at: /content/drive/MyDrive/Anusha/Financial Analytics/Data/Historical_Financial_Data.csv

In [4]:
# Load the Historical Financial Dataset

historical_df = pd.read_csv(file_path)

historical_df.head()

,Company,Ticker,Sector,Industry,Financial Year,Revenue,Gross Profit,Operating Income,EBIT,EBITDA,...,Current Assets,Cash,Total Liabilities,Total Debt,Shareholders Equity,Operating Cash Flow,Investing Cash Flow,Financing Cash Flow,Capital Expenditure,Free Cash Flow
0,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2026,1.002670e+12,2.620093e+11,8.437760e+10,1.991757e+11,2.605291e+11,...,6.117604e+11,6.266670e+10,1.724221e+12,1.066218e+12,8.092595e+11,2.356910e+10,-2.843801e+11,2.848447e+11,-3.336912e+11,-3.101221e+11
1,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2025,9.771108e+11,3.276082e+11,1.044309e+11,1.536634e+11,1.957767e+11,...,4.094422e+11,3.105780e+10,1.416651e+12,9.147260e+11,5.031397e+11,4.513100e+10,-2.696661e+11,2.265534e+11,-2.987914e+11,-2.536604e+11
2,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2024,9.631615e+11,3.114884e+11,9.012870e+10,8.644370e+10,1.168652e+11,...,3.702690e+11,2.306550e+10,1.165456e+12,6.531015e+11,3.907609e+11,1.031219e+11,-1.908218e+11,8.878680e+10,-2.236591e+11,-1.205372e+11
3,Adani Enterprises Limited,ADANIENT.NS,Energy,Thermal Coal,2023,1.273896e+12,2.061800e+11,6.827980e+10,6.241290e+10,8.677430e+10,...,3.728228e+11,1.882330e+10,1.035978e+12,5.301260e+11,3.305101e+11,1.762646e+11,-1.686009e+11,-1.197520e+10,-1.472472e+11,2.901740e+10
4,Adani Ports and Special Economic Zone Limited,ADANIPORTS.NS,Industrials,Marine Shipping,2026,3.873577e+11,2.343314e+11,1.745082e+11,1.859993e+11,2.411731e+11,...,2.197483e+11,5.161550e+10,8.633328e+11,6.323616e+11,9.612530e+11,2.035625e+11,-1.319070e+11,-5.483400e+10,-1.532031e+11,5.035940e+10

In [5]:
# ============================================================
# Select a company for analysis.
#
# The Historical Financial Dataset contains financial
# information for multiple companies.
#
# In this exercise, you will analyse the historical
# financial information of Tata Consultancy Services (TCS).
#
# After completing this exercise, you may replace the
# ticker symbol with any other company in the dataset and
# repeat the analysis.
# ============================================================

company_data = historical_df[
    historical_df["Ticker"] == "TCS.NS"
].copy()

# Arrange the financial data in chronological order
company_data = company_data.sort_values("Financial Year")

# Display the company's historical financial information
company_data

,Company,Ticker,Sector,Industry,Financial Year,Revenue,Gross Profit,Operating Income,EBIT,EBITDA,...,Current Assets,Cash,Total Liabilities,Total Debt,Shareholders Equity,Operating Cash Flow,Investing Cash Flow,Financing Cash Flow,Capital Expenditure,Free Cash Flow
207,NaN,TCS.NS,Technology,Information Technology Services,2023,2.254580e+12,1.056990e+12,5.437700e+11,5.768600e+11,6.270800e+11,...,1.102700e+12,7.115000e+10,5.244500e+11,7.688000e+10,9.042400e+11,4.196500e+11,3.900000e+08,-4.787800e+11,-3.100000e+10,3.886500e+11
206,NaN,TCS.NS,Technology,Information Technology Services,2024,2.408930e+12,1.080220e+12,5.942500e+11,6.277500e+11,6.776000e+11,...,1.129840e+12,9.007000e+10,5.513000e+11,8.021000e+10,9.048900e+11,4.433800e+11,6.026000e+10,-4.853600e+11,-2.674000e+10,4.166400e+11
205,NaN,TCS.NS,Technology,Information Technology Services,2025,2.553240e+12,1.096410e+12,6.229300e+11,6.612700e+11,7.136900e+11,...,1.230110e+12,8.331000e+10,6.385800e+11,9.392000e+10,9.475600e+11,4.890800e+11,-2.318000e+10,-4.743800e+11,-3.937000e+10,4.497100e+11
204,NaN,TCS.NS,Technology,Information Technology Services,2026,2.670210e+12,1.204180e+12,6.702200e+11,6.671400e+11,7.227400e+11,...,1.357050e+12,6.405000e+10,7.389400e+11,1.128300e+11,1.072400e+12,5.209400e+11,-1.284500e+11,-4.213300e+11,-4.146000e+10,4.794800e+11

## Understanding Historical Cash Flows

The table above displays the historical cash flows of Tata Consultancy Services (TCS).

Before learning the Time Value of Money, take a few minutes to examine the data.

### Think About It

1. Which financial year has the highest Operating Cash Flow?
2. Is Free Cash Flow increasing or decreasing over time?
3. Why do you think Operating Cash Flow and Free Cash Flow are different?
4. If you were an investor, which cash flow would you focus on and why?

In this chapter, you will use these historical cash flows to understand how financial analysts evaluate cash received at different points in time using the Time Value of Money.

In [6]:
# ============================================================
# Display the historical cash flows of TCS.
#
# Time Value of Money focuses on analysing cash flows
# occurring at different points in time.
#
# Therefore, the Operating Cash Flow and Free Cash Flow
# of TCS will be used throughout this chapter.
# ============================================================

cash_flows = company_data[
    [
        "Financial Year",
        "Operating Cash Flow",
        "Free Cash Flow"
    ]
]

cash_flows

     Financial Year  Operating Cash Flow  Free Cash Flow
207            2023         4.196500e+11    3.886500e+11
206            2024         4.433800e+11    4.166400e+11
205            2025         4.890800e+11    4.497100e+11
204            2026         5.209400e+11    4.794800e+11

# 5.1 Present Value (PV)

The historical cash flows of Tata Consultancy Services (TCS) represent the cash generated by the company over different financial years. While these cash flows provide valuable insights into the company's financial performance, they cannot be directly compared because they occur at different points in time.

According to the **Time Value of Money (TVM)** principle, the value of money changes over time. A cash flow received today is worth more than the same cash flow received in the future because today's money can be invested to earn a return.

Therefore, before comparing or evaluating cash flows occurring at different time periods, financial analysts convert them to a common point in time.

One of the most widely used techniques for doing this is **Present Value (PV)**.

Present Value answers the following question:

> **"How much is a future cash flow worth today?"**

## Present Value of Multiple Cash Flows

Suppose an investment is expected to generate cash flows over several years. Since these cash flows occur at different points in time, they cannot be added directly.

To determine their value today, each future cash flow must first be discounted using an appropriate discount rate.

The Present Value (PV) of the cash flows is obtained by adding the discounted values of all future cash flows.

In this section, we will:

1. Create a Python function to calculate the Present Value of multiple cash flows.
2. Test the function using a simple example.
3. Apply the same function to the historical cash flows of Tata Consultancy Services (TCS).

In [7]:
# ============================================================
# Function: find_pv()
#
# Purpose:
# Calculate the Present Value (PV) of a series of future
# cash flows.
#
# Parameters:
# r         : Discount Rate
# cashflows : List of future cash flows
#
# Assumption:
# The first cash flow occurs at the end of Year 1.
# ============================================================

def find_pv(r, cashflows):

    pv = 0

    for i in range(len(cashflows)):
        pv = pv + cashflows[i] / ((1 + r) ** (i + 1))

    return pv

## Understanding the `find_pv()` Function

Let's understand how the function works step by step.

### Function Definition

```python
def find_pv(r, cashflows):
```

- `def` tells Python that we are creating a new function.
- `find_pv` is the name of the function.
- `r` represents the **discount rate**.
- `cashflows` is a list containing the future cash flows.

For example:

```python
cashflows = [100, 200, 300, 400, 500]
```

represents:

| Year | Cash Flow (₹) |
|------|--------------:|
|1|100|
|2|200|
|3|300|
|4|400|
|5|500|

---

### Step 1: Initialize the Present Value

```python
pv = 0
```

We create a variable named `pv` and set it to zero.

This variable will store the **total present value** of all future cash flows.

Initially,

```text
PV = 0
```

---

### Step 2: Loop Through Each Cash Flow

```python
for i in range(len(cashflows)):
```

- `len(cashflows)` returns the number of cash flows.
- In this example:

```python
len(cashflows)
```

returns

```text
5
```

Therefore,

```python
range(5)
```

produces

```text
0, 1, 2, 3, 4
```

Python uses **zero-based indexing**, so:

| i | Year | Cash Flow |
|---|------|----------:|
|0|1|100|
|1|2|200|
|2|3|300|
|3|4|400|
|4|5|500|

Notice that **Year = i + 1**.

---

### Step 3: Discount Each Cash Flow

```python
pv = pv + cashflows[i] / ((1 + r) ** (i + 1))
```

This line discounts one cash flow at a time and adds it to the total Present Value.

For the first cash flow:

```python
100 / (1.10)^1
```

For the second:

```python
200 / (1.10)^2
```

For the third:

```python
300 / (1.10)^3
```

The process continues until every cash flow has been discounted.

---

### Step 4: Return the Result

```python
return pv
```

Once all cash flows have been discounted and added together, the function returns the final Present Value.

For the example:

```python
cashflows = [100, 200, 300, 400, 500]
r = 0.10
```

the function returns approximately

```text
1065.26
```

This means that receiving ₹100, ₹200, ₹300, ₹400, and ₹500 over the next five years is equivalent to receiving approximately **₹1,065.26 today**, assuming a discount rate of **10%**.

In [8]:
# ============================================================
# Example: Present Value of Multiple Cash Flows
# ============================================================

cashflows = [100, 200, 300, 400, 500]

discount_rate = 0.10

pv = find_pv(discount_rate, cashflows)

print("Present Value =", round(pv, 2))

Present Value = 1065.26

## Practical Demonstration: Present Value of TCS Cash Flows

The previous example demonstrated how the Present Value of a series of future cash flows can be calculated using a simple set of numbers.

In practice, financial analysts rarely work with hypothetical cash flows. Instead, they evaluate the future cash flows generated by real companies to support investment and valuation decisions.

In this demonstration, we will use the historical **Operating Cash Flow** of Tata Consultancy Services (TCS) and calculate its Present Value using the `find_pv()` function created earlier.

> **Note:** For learning purposes, we assume that the historical operating cash flows represent future expected cash flows. In practice, analysts typically forecast future cash flows before discounting them to their present value.

In [12]:
# ============================================================
# Extract the Operating Cash Flows of TCS.
#
# The Operating Cash Flow values are converted into a Python
# list because the find_pv() function expects a list of
# future cash flows as input.
# ============================================================

tcs_cashflows = company_data["Operating Cash Flow"].tolist()

print("TCS Operating Cash Flows:")
print(tcs_cashflows)

TCS Operating Cash Flows:
[419650000000.0, 443380000000.0, 489080000000.0, 520940000000.0]

# ============================================================
# Practical Demonstration:
# Extract the Operating Cash Flows of Tata Consultancy
# Services (TCS).
#
# The company_data DataFrame contains the historical
# financial information of TCS, including the Financial
# Year, Revenue, Net Income, Operating Cash Flow, and
# several other financial variables.
#
# In this demonstration, we are interested only in the
# Operating Cash Flow because Present Value (PV) is
# calculated using future cash flows.
#
# The statement:
#
# company_data["Operating Cash Flow"]
#
# selects the 'Operating Cash Flow' column from the
# DataFrame.
#
# However, the find_pv() function expects a Python list
# as its input rather than a DataFrame column.
#
# Therefore, the tolist() function is used to convert the
# selected column into a Python list.
# ============================================================

# Extract the Operating Cash Flow column and convert it
# into a Python list.
tcs_cashflows = company_data["Operating Cash Flow"].tolist()

# Display a heading so that the output is easy to identify.
print("TCS Operating Cash Flows:")

# Display the extracted list of Operating Cash Flows.
# Each value in the list represents the Operating Cash Flow
# of TCS for one financial year.
print(tcs_cashflows)

In the single-investment example, we explicitly specify the time period (t or n). When working with multiple cash flows, the function automatically treats the first cash flow as Year 1, the second as Year 2, and so on. Therefore, a separate time variable is not required.

Note: The historical operating cash flows of TCS are used only to demonstrate the Python implementation of the Present Value concept. In real financial analysis, Present Value is calculated using forecasted future cash flows, not historical cash flows.

### Example

For demonstration purposes, assume that the historical Operating Cash Flows are also the expected cash flows for the next five years.

Historical Operating Cash Flows:

- Year 1: 44,531
- Year 2: 48,920
- Year 3: 52,341
- Year 4: 56,187
- Year 5: 60,215

In [13]:
# Assume these are the forecast cash flows
forecast_cashflows = [44531, 48920, 52341, 56187, 60215]

pv = find_pv(0.10, forecast_cashflows)

print("Present Value =", round(pv, 2))

Present Value = 196002.3

# 5.X Future Value (FV)

The Future Value (FV) of money represents the value of an investment or a series of cash flows at a specified point in the future.

While Present Value discounts future cash flows to determine their value today, Future Value compounds cash flows forward to estimate how much they will be worth at a future date.

Future Value is commonly used to answer questions such as:

- How much will an investment be worth after a certain number of years?
- How much will regular cash flows accumulate to in the future?
- What is the future worth of today's investment?

## Future Value of Multiple Cash Flows

Suppose an investment generates cash flows over several years.

Since each cash flow is received at a different point in time, every cash flow must be compounded to the same future date before they can be added together.

The function developed in this section calculates the Future Value of a series of cash flows.

In [14]:
# ============================================================
# Purpose
# ============================================================
#
# Create a function to calculate the Future Value (FV)
# of a series of cash flows.
#
# ============================================================
# Background
# ============================================================
#
# Unlike Present Value, which discounts future cash flows
# back to today's value, Future Value compounds each cash
# flow forward to a common future date.
#
# The first cash flow is compounded for the maximum
# number of years, whereas the last cash flow is
# compounded for zero years because it already occurs at
# the final time period.
#
# ============================================================
# Function Definition
# ============================================================

def find_fv(r, cashflows):

    # Determine the total number of cash flows
    k = len(cashflows)

    # Initialize Future Value
    fv = 0

    # Compound each cash flow to the end of Year k
    for i in range(k):
        fv = fv + cashflows[i] * ((1 + r) ** (k - i - 1))

    # Return the total Future Value
    return fv

PV asks: "How far into the future is this cash flow?" So we discount using (i + 1).
FV asks: "How many years remain until the final year?" So we compound using (k - i - 1).

## Understanding the `find_fv()` Function

Let's understand how the function calculates the Future Value of multiple cash flows.

### Function Definition

```python
def find_fv(r, cashflows):
```

- `def` tells Python that we are creating a new function.
- `find_fv` is the name of the function.
- `r` represents the annual interest (or discount) rate.
- `cashflows` is a Python list containing the cash flows.

For example,

```python
cashflows = [100, 200, 300, 400, 500]
```

represents:

| Year | Cash Flow (₹) |
|------|--------------:|
|1|100|
|2|200|
|3|300|
|4|400|
|5|500|

---

### Step 1: Count the Number of Cash Flows

```python
k = len(cashflows)
```

The `len()` function counts the number of elements in the list.

For example,

```python
cashflows = [100, 200, 300, 400, 500]
```

contains **5** cash flows.

Therefore,

```python
k = len(cashflows)
```

becomes

```python
k = 5
```

The variable `k` represents the **total number of cash flows**.

Using `len()` makes the function flexible because it automatically works for any number of cash flows.

---

### Step 2: Initialize the Future Value

```python
fv = 0
```

A variable named `fv` is created to store the total Future Value.

Initially,

```text
Future Value = 0
```

---

### Step 3: Process Each Cash Flow

```python
for i in range(k):
```

Since `k = 5`,

```python
range(5)
```

produces

```text
0, 1, 2, 3, 4
```

Remember that Python uses **zero-based indexing**.

| Python Index | Financial Year |
|--------------|---------------:|
|0|Year 1|
|1|Year 2|
|2|Year 3|
|3|Year 4|
|4|Year 5|

---

### Step 4: Compound Each Cash Flow

```python
fv = fv + cashflows[i] * ((1 + r) ** (k - i - 1))
```

This statement compounds every cash flow to the end of the final year.

For five cash flows:

| Year | Cash Flow | Years Compounded |
|------|----------:|-----------------:|
|1|100|4|
|2|200|3|
|3|300|2|
|4|400|1|
|5|500|0|

Therefore,

```text
100 × (1.10)^4
```

```text
200 × (1.10)^3
```

```text
300 × (1.10)^2
```

```text
400 × (1.10)^1
```

```text
500 × (1.10)^0
```

Notice that the **last cash flow is not compounded**, because it already occurs at the final year.

---

### Step 5: Return the Result

```python
return fv
```

After all cash flows have been compounded and added together, the function returns the total Future Value.

This value represents the accumulated value of all the cash flows at the end of the final year.

In [ ]:
# ============================================================
# Example: Future Value of Multiple Cash Flows
# ============================================================

cashflows = [100, 200, 300, 400, 500]

r = 0.10

fv = find_fv(r, cashflows)

print("Future Value =", round(fv, 2))

## Practical Demonstration: Future Value of TCS Operating Cash Flows

In the previous example, we calculated the Future Value of a simple series of cash flows.

In practice, financial analysts often project future cash flows before calculating their Future Value. However, for learning purposes, we will use the historical Operating Cash Flows of Tata Consultancy Services (TCS) to demonstrate how the `find_fv()` function works.

**Note:** The historical cash flows are used only to illustrate the Future Value calculation. In real-world financial analysis, future projected cash flows are generally used.

In [15]:
# ============================================================
# Purpose
# ============================================================
#
# Calculate the Future Value (FV) of the Operating Cash
# Flows of Tata Consultancy Services (TCS).
#
# ============================================================
# Background
# ============================================================
#
# The find_fv() function compounds each cash flow to the
# end of the final year and then adds all the compounded
# cash flows together.
#
# For demonstration purposes, we use the historical
# Operating Cash Flows of TCS.
#
# ============================================================
# Code
# ============================================================

# Extract the Operating Cash Flows of TCS
tcs_cashflows = company_data["Operating Cash Flow"].tolist()

# Display the extracted cash flows
print("TCS Operating Cash Flows:")
print(tcs_cashflows)

# Specify the annual interest rate
r = 0.10

# Calculate the Future Value
tcs_fv = find_fv(r, tcs_cashflows)

# ============================================================
# Output
# ============================================================

print("Future Value of TCS Operating Cash Flows =", round(tcs_fv, 2))

TCS Operating Cash Flows:
[419650000000.0, 443380000000.0, 489080000000.0, 520940000000.0]
Future Value of TCS Operating Cash Flows = 2153971950000.0

Step 1
───────────────
Create Function

def find_fv(...):
       ↓
Python stores the function in memory.

(No calculation is performed.)

────────────────────────────────────────

Step 2
───────────────

find_fv(0.10, tcs_cashflows)

       ↓

Python enters the function.

       ↓

r = 0.10

cashflows = tcs_cashflows

k = len(cashflows)

fv = ...

return fv

       ↓

Answer returned to the notebook.

# 5.3 Present Value of an Annuity (PVA)

An annuity is a series of equal cash flows received or paid at
regular intervals over a specified period.

The Present Value of an Annuity (PVA) calculates the value today
of these equal future cash flows.

In this section, we will:
1. Create a Python function to calculate PVA.
2. Test the function using a simple example.
3. Apply the concept to a practical financial scenario.

## PVA Formula

PVA = (A / r) × (1 - 1 / (1 + r)^k)

Where:

A = Equal periodic cash flow
r = Discount rate per period
k = Number of periods

In [16]:
def find_pva(r, k, A):

    pva = (A / r) * (1 - (1 / (1 + r) ** k))

    return pva

In [17]:
r = 0.10
k = 5
A = 100

pva = find_pva(r, k, A)

print("Present Value of Annuity =", round(pva, 2))

Present Value of Annuity = 379.08

In [18]:
# ============================================================
# TCS Practical Example – Present Value of an Annuity
# ============================================================

# Assumed annual Operating Cash Flow
# for the next 5 years
A = 50000

# Discount rate
r = 0.10

# Number of years
k = 5

# Calculate the Present Value of the annuity
tcs_pva = find_pva(r, k, A)

# Display the result
print("TCS Assumed Annual Cash Flow =", A)
print("Discount Rate =", r)
print("Number of Years =", k)
print("Present Value of TCS Cash Flows =", round(tcs_pva, 2))

TCS Assumed Annual Cash Flow = 50000
Discount Rate = 0.1
Number of Years = 5
Present Value of TCS Cash Flows = 189539.34

# 5.4 Future Value of an Annuity (FVA)

The Future Value of an Annuity (FVA) calculates the accumulated
value of a series of equal cash flows at the end of the final
period.

In this section, we will:

1. Create a Python function to calculate FVA.
2. Test the function using a simple example.
3. Apply the concept to a practical financial scenario.

## Future Value of an Annuity Formula

FVA = A × ((1 + r)^k - 1) / r

Where:

A = Equal periodic cash flow
r = Interest rate per period
k = Number of periods

The formula assumes a normal (ordinary) annuity, where payments
occur at the end of each period.

PVA asks: "What are these equal future payments worth today?"
FVA asks: "What will these equal payments accumulate to by the end?

In [19]:
# ============================================================
# Function: find_fva()
#
# Purpose:
# Calculate the Future Value of a normal annuity.
#
# Parameters:
# r : Interest rate per period
# k : Number of periods
# A : Equal cash flow received or paid in each period
#
# ============================================================

def find_fva(r, k, A):

    # Calculate the Future Value of the annuity
    fva = A * (((1 + r) ** k - 1) / r)

    # Return the calculated Future Value
    return fva

## Understanding the `find_fva()` Function

The function requires three inputs:

r → Interest rate per period

k → Number of periods

A → Equal cash flow in each period

For example:

r = 0.10
k = 5
A = 100

means that ₹100 is received or invested at the end of each
year for 5 years, at an annual interest rate of 10%.

The function then applies the Future Value of an Annuity formula
and returns the accumulated value at the end of the fifth year.

In [20]:
# ============================================================
# Example: Future Value of an Annuity
# ============================================================

# Annual interest rate
r = 0.10

# Number of periods
k = 5

# Equal annual cash flow
A = 100

# Calculate the Future Value of the annuity
fva = find_fva(r, k, A)

# Display the result
print("Future Value of Annuity =", round(fva, 2))

Future Value of Annuity = 610.51

In [21]:
# ============================================================
# TCS Practical Example – Future Value of an Annuity
# ============================================================

# Assumed annual Operating Cash Flow
# for the next 5 years
A = 50000

# Annual interest rate
r = 0.10

# Number of years
k = 5

# Calculate the Future Value of the annuity
tcs_fva = find_fva(r, k, A)

# Display the inputs and result
print("TCS Assumed Annual Cash Flow =", A)
print("Interest Rate =", r)
print("Number of Years =", k)
print("Future Value of TCS Cash Flows =", round(tcs_fva, 2))

TCS Assumed Annual Cash Flow = 50000
Interest Rate = 0.1
Number of Years = 5
Future Value of TCS Cash Flows = 305255.0

# 5.5 Present Value of an Annuity Due

An annuity due is a series of equal cash flows where the
cash flow occurs at the beginning of each period.

In a normal (ordinary) annuity, the cash flow occurs at the
end of each period.

The Present Value of an Annuity Due can be calculated by
multiplying the Present Value of a normal annuity by (1 + r).

PVA Due = PVA × (1 + r)

In this section, we will create a Python function to calculate
the Present Value of an Annuity Due.

In [22]:
# ============================================================
# Function: find_pvad()
#
# Purpose:
# Calculate the Present Value of an Annuity Due.
#
# An annuity due receives the cash flow at the beginning
# of each period.
# ============================================================

def find_pvad(r, k, A):

    # First calculate the Present Value of the normal annuity
    pva = find_pva(r, k, A)

    # Since the cash flows occur one period earlier,
    # multiply the normal PVA by (1 + r)
    pvad = pva * (1 + r)

    # Return the Present Value of the annuity due
    return pvad

## Example: Present Value of an Annuity Due

Suppose we receive ₹100 at the beginning of every year
for 5 years.

Assume a discount rate of 10%.

We can calculate the Present Value using the `find_pvad()`
function.

In [23]:
# Annual discount rate
r = 0.10

# Number of periods
k = 5

# Equal cash flow
A = 100

# Calculate Present Value of Annuity Due
pvad = find_pvad(r, k, A)

print("Present Value of Annuity Due =", round(pvad, 2))

Present Value of Annuity Due = 416.99

In [24]:
# ============================================================
# TCS Practical Example – Present Value of an Annuity Due
# ============================================================

# Assumed annual cash flow
A = 50000

# Discount rate
r = 0.10

# Number of years
k = 5

# Calculate PVA Due
tcs_pvad = find_pvad(r, k, A)

print("TCS Assumed Annual Cash Flow =", A)
print("Discount Rate =", r)
print("Number of Years =", k)
print("Present Value of TCS Annuity Due =", round(tcs_pvad, 2))

TCS Assumed Annual Cash Flow = 50000
Discount Rate = 0.1
Number of Years = 5
Present Value of TCS Annuity Due = 208493.27

# 5.6 Future Value of an Annuity Due

An annuity due is a series of equal cash flows where the cash
flow occurs at the beginning of each period.

The Future Value of an Annuity Due can be calculated by
multiplying the Future Value of a normal annuity by (1 + r).

FVA Due = FVA × (1 + r)

In [25]:
# ============================================================
# Function: find_fvad()
#
# Purpose:
# Calculate the Future Value of an Annuity Due.
#
# An annuity due receives the cash flow at the beginning
# of each period.
# ============================================================

def find_fvad(r, k, A):

    # First calculate the Future Value of the normal annuity
    fva = find_fva(r, k, A)

    # Since the cash flows occur one period earlier,
    # multiply the normal FVA by (1 + r)
    fvad = fva * (1 + r)

    # Return the Future Value of the annuity due
    return fvad

## Example: Future Value of an Annuity Due

Suppose we receive ₹100 at the beginning of every year
for 5 years.

Assume an interest rate of 10%.

We can calculate the Future Value using the `find_fvad()`
function.

In [27]:
# Annual interest rate
r = 0.10

# Number of periods
k = 5

# Equal annual cash flow
A = 100

# Calculate Future Value of Annuity Due
fvad = find_fvad(r, k, A)

print("Future Value of Annuity Due =", round(fvad, 2))

Future Value of Annuity Due = 671.56

In [28]:
# ============================================================
# TCS Practical Example – Future Value of an Annuity Due
# ============================================================

# Assumed annual cash flow
A = 50000

# Annual interest rate
r = 0.10

# Number of years
k = 5

# Calculate Future Value of the annuity due
tcs_fvad = find_fvad(r, k, A)

print("TCS Assumed Annual Cash Flow =", A)
print("Interest Rate =", r)
print("Number of Years =", k)
print("Future Value of TCS Annuity Due =", round(tcs_fvad, 2))

TCS Assumed Annual Cash Flow = 50000
Interest Rate = 0.1
Number of Years = 5
Future Value of TCS Annuity Due = 335780.5

Because the annuity-due payments occur earlier, they have one additional period of compounding, making the future value higher.